server:
  port: 8002

spring:
  application:
    name: USER-SERVICE

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps: 5
        waitDuration: 3s

  ratelimiter:
    instances:
      # RateLimiter object used in RateLimitingService.basicExample()
      basicExample:
        limitForPeriod: 1
        limitRefreshPeriod: 10s
        timeoutDuration: 20s
      # RateLimiter object used in RateLimitingService.timeoutExample()
      timeoutExample:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost